import { DataSource, DataSourceOptions } from "typeorm";

// Optional: load .env automatically when running locally (safe in prod too)
import "dotenv/config";

async function importAllWards() {
  const databaseUrl = process.env.DATABASE_URL;

  const options: DataSourceOptions = {
    type: "postgres",
    url: databaseUrl,
    entities: [],
    synchronize: false,
  };

  console.log(
    databaseUrl
      ? "Using DATABASE_URL (prod/server)\n"
      : "DATABASE_URL not set → using localhost config (dev)\n",
  );

  const dataSource = new DataSource(options);

  await dataSource.initialize();
  console.log("✓ Database connected\n");

  // Delete existing wards for fresh import
  console.log("Deleting existing wards...");
  await dataSource.query("DELETE FROM wards");
  console.log("✓ Existing wards deleted\n");

  // Helper to strip "X - " prefix from ward names (you defined it, but you never used it)
  const strip = (n: string) => n.replace(/^\d+\s*-\s*/, "").trim();

  const corps = [
    {
      name: "Central",
      prefix: "C",
      wards: [
        "Ramaswamy Palya",
        "Jayamahal",
        "Vasanth Nagar",
        "Sampangirama Nagar",
        "Shivajinagar",
        "Bharathi Nagar",
        "K Kamaraj",
        "Halasuru",
        "Hoysala Nagara Central",
        "Cox Town",
        "Old Baiyappanahalli",
        "Kasturi Nagar",
        "Krishnaiahnapalya",
        "Nagavarapalya",
        "Indiranagar",
        "New Thippasandra",
        "Kaggadasapura",
        "G.M Palya",
        "Jeevan Bhimanagar",
        "Kodihalli",
        "Konena Agrahara",
        "Domluru",
        "Jogpalya",
        "Agaram",
        "Ashokanagar",
        "Vannarpet",
        "Ambedkarnagar",
        "Neelasandra",
        "Austin Town",
        "Vinayakanagar",
        "Shanthinagar",
        "SilverJubliee Park",
        "Dharmaraya Swamy Temple",
        "D.V Gundappa",
        "Hombegowda Nagara",
        "Someshwara Nagara",
        "BHEL",
        "Kanakanapalya",
        "Venkat Reddy Nagara",
        "Ashoka Pillar",
        "V.V Puram",
        "Sunkenahalli",
        "Devaraj Urs",
        "Chamarajpet",
        "K.R Market",
        "Cheluvadi Palya",
        "IPD Salappa",
        "Azad Nagar",
        "Kasturbha Nagar",
        "JJR Nagara",
        "Old Guddadahalli",
        "Padarayanapura",
        "Rayapuram",
        "Binnypete",
        "Bhuvaneshwari Nagar",
        "Gopalpura",
        "Cottonpete",
        "Chickpete",
        "Nehru Nagar",
        "Seshadripuram",
        "Dattatreya",
        "Swatantra Palya",
        "Okalipuram",
      ],
    },
    {
      name: "East",
      prefix: "E",
      wards: [
        "K Narayanapura",
        "Horamavu agara",
        "Chellakere",
        "Babusapalya",
        "Hoysala Nagara East",
        "Kalkere",
        "K Chennasandra",
        "Anandapura",
        "Bhattarahalli",
        "Basavanapura",
        "Krishna Nagar",
        "Devasandra",
        "Rajarajeshwari Temple",
        "K.R Pura",
        "Ramamurthy Nagara",
        "Kotthur",
        "Vijinapura",
        "Dooravaninagar",
        "K.S. Nissar Ahmed",
        "A Narayanapura",
        "Uday Nagar",
        "Mahadevapura",
        "Sangama",
        "Vignananagara",
        "L.B Shastri Nagar",
        "Jagadish Nagar",
        "Vibhootipura",
        "Byrathi",
        "Hoodi",
        "Belathur",
        "Kadugodi",
        "Channasandra",
        "S.M Krishna",
        "Kaveri Nagara",
        "Garudachar Palya",
        "Bharath Aikya",
        "Kundalahalli",
        "Whitefield",
        "Hagaduru",
        "Varthur",
        "Munnenkolalu",
        "Priyadarshini",
        "Dodda Nekkundi",
        "Ashwath Nagar",
        "Marathahalli",
        "Yamalur",
        "Bellanduru",
        "Panathur",
        "Doddakannelli",
        "Gunjur",
      ],
    },
    {
      name: "North",
      prefix: "N",
      wards: [
        "Raja Kempegowda",
        "Aerocity",
        "Chowdeshwari Nagara",
        "Nyayanga Badavane",
        "Yelahanka Satellite Town",
        "Doddabetttahalli",
        "Attur",
        "Singapura",
        "Kuvempunagara",
        "Vidyaranyapura",
        "Doddabommasandra",
        "Thindlu",
        "Kodigehalli",
        "Rajivgandhi nagar",
        "Byatarayanapura",
        "Amurthahalli",
        "Jakkur",
        "Kempapura",
        "Thanisandra",
        "Sampigehalli",
        "Kogilu",
        "Nagavara",
        "Hennur",
        "HBR Layout",
        "Govinda Pura",
        "Samadhana Nagar",
        "K.G.Halli",
        "Venkateshpuram",
        "Lingarajpura",
        "Kacharakanahalli",
        "Kalyan Nagar",
        "Banaswadi",
        "HRBR Layout",
        "Subbayanapalya",
        "Kammanahalli",
        "Maruthi Seva Nagara",
        "Jeevanahalli",
        "Shampura",
        "Kaval Byrasandra",
        "Shakthi Nagar",
        "Periyar Nagar",
        "Aruna Asif Ali",
        "Varalakshmi Nagar",
        "Doddanna Nagar",
        "Khusal Nagar",
        "Sagayapuram",
        "Pulakeshi Nagar",
        "S.K Garden",
        "Jaya Chamarajendra Nagara",
        "Dinnur",
        "Manorayanapalya",
        "Vishwanatha Nagenahalli",
        "R.T Nagar",
        "Gangenahalli",
        "Ganganagar",
        "Hebbal",
        "Bhoopasandra",
        "Nagashettyhalli",
        "Geddalahalli",
        "Jalahalli",
        "HMT",
        "Brundavana nagara",
        "J.P park",
        "Yeshwanthpura",
        "Abbigere",
        "Kammagondanahalli",
        "Shettihalli",
        "Mallasandra",
        "Bagalagunte",
        "Manjunatha nagar",
        "Nele Maheshwaramma Temple",
        "Dasarahalli",
      ],
    },
    {
      name: "South",
      prefix: "S",
      wards: [
        "Padmanabhanagar",
        "Kadirenahalli",
        "Yarab Nagar",
        "Banashakari Temple",
        "kaneMuneshwara",
        "Gowdanapalya",
        "Byrasandra",
        "Tilak nagara",
        "N.A.L Layout",
        "Abdul kalam nagar",
        "Jayanagar East",
        "Pattabhiramanagar",
        "Marenahalli South",
        "J.P Nagar",
        "Shakambarinagara",
        "Sarakki",
        "N.S.Palya",
        "Viswamanava Kuvempu",
        "Tavarekere",
        "Madiwala",
        "Chikka Adugodi",
        "S.G.Palya",
        "Lakkasandra",
        "A Adugodi",
        "National games village",
        "Ejipura",
        "Sri Lakshmi Devi",
        "Kormangala East",
        "Kormangala West",
        "Jakkasandra",
        "Kasavanahalli",
        "Kudlu",
        "Naganathapura",
        "Chikkathoguru",
        "Vishwapriya Nagara",
        "Beguru",
        "Yelenahalli",
        "Doddakammanahalli",
        "Gottigere",
        "Anjanapura",
        "Kothanur",
        "RBI Layout",
        "Beereshwara Nagar",
        "Hari Nagar",
        "Konanakunte",
        "Yelechenahalli",
        "Chandranagara",
        "Vasantapura",
        "Uttarahalli",
        "Sarvabhouma Nagar",
        "Subramanyapura",
        "Talagattpura",
        "Jaraganahalli",
        "Kengal Hanumanthaiah South",
        "Puttenahalli",
        "Doresanipalya",
        "Hulimavu",
        "Arakere",
        "Vijaya Bank Layout",
        "Bilekahalli",
        "Kodi Chikkanahalli",
        "Devarachikkanahalli",
        "Bommanahalli",
        "Hongasandra",
        "Garvebavi palya",
        "Singasandra",
        "Bandepalya",
        "Mangammana Palya",
        "Hosapalya",
        "Iblur",
        "Agara",
        "HSR Layout",
      ],
    },
    {
      name: "West",
      prefix: "W",
      wards: [
        "Nagasandra",
        "Chokkasandra",
        "Nelagadaranahalli",
        "Parvathi Nagar",
        "Rajeshwarinagar",
        "Shivapura",
        "Rajagopala Nagara",
        "Hegganahalli",
        "Srigandhanagar",
        "Sunkadakatte",
        "Dodda Bidarakallu",
        "Andrahalli",
        "Nada prabhu Kempegowda Nagara",
        "Herohalli",
        "Byadarahalli",
        "Ullal",
        "Nagadevanahalli",
        "Kengal Hanumanthaiah",
        "Shivanpalya",
        "Kengeri Kote",
        "Kengari",
        "Bangarappa Nagara",
        "Rajarajeshwari Nagara",
        "Jnana Bharathi",
        "Vinayaka Layout",
        "Mallathahalli",
        "Srigandada Kaval",
        "Kottegepalya",
        "Chowdeshwari Nagar",
        "Kempegowda Layout",
        "Freedom Fighter",
        "Laggere",
        "Lakshmi Devi Nagar",
        "Peenya",
        "Goraguntepalya",
        "Nalwadi Krishnaraja Wadiyar",
        "Dr. Puneeth Rajkumar",
        "Nandini Layout",
        "Jai Maruthi Nagar",
        "Mahalakshmipuram",
        "Nagapura",
        "Raja Mayura Varma",
        "Kethamaranahalli",
        "Shankar Mutt",
        "Shakthi Ganapathi Nagara",
        "Kamalanagara",
        "Vrishabhavathi Nagar",
        "Mathikere",
        "Aramane Nagara",
        "Sadashiva Nagara",
        "Rajamahal",
        "Kodandarampura",
        "Malleshwaram",
        "Subedarpalya",
        "Subramanyanagara",
        "Gayathri Nagara",
        "Kuvempu",
        "Dayanand Nagara",
        "Bandi Reddy Circle Ward",
        "Prakash Nagara",
        "Da.Ra. Bendre",
        "Rama Mandira",
        "Rajajinagara",
        "Shivanagara",
        "Manjunath Nagara",
        "Sane Guruvana Halli",
        "Basaveshwara Nagara",
        "Kamakshipalya",
        "Agrahara Dasarahalli",
        "Dr Rajkumar",
        "Thimmenahalli",
        "Kaveripura",
        "Dr. Vishnuvardhan",
        "Pattegar Palya",
        "Marenahalli West",
        "Moodalapalya",
        "Maruthi Mandira",
        "Anubhava Nagara",
        "Nagarbhavi",
        "Chandra Layout",
        "Nayanda Halli",
        "Attigupe",
        "Hampi Nagar",
        "Hosahalli",
        "Adi Chunchanagiri",
        "Vidyaranyanagara",
        "K.P Agrahara",
        "Sangolli Rayanna",
        "Bapuji Nagara",
        "Krishnadevaraya",
        "Gali Anjaneya Temple",
        "Muneshwara Block",
        "Avalahalli",
        "Deepanjali Nagara",
        "Swamy Vivekananda",
        "Kathriguppe",
        "Srinivasa Nagara",
        "Ashoka Nagara",
        "T.R Shamanna Nagar",
        "Srinagar",
        "Kempambudhi",
        "Hanumanthanagar",
        "N.R Colony",
        "Thyagarajnagar",
        "Yediyuru",
        "Devagiri Temple",
        "Dharmagiri",
        "Ganesh Mandira",
        "Kamakya Layout",
        "Chikkalasandra",
        "Ittamadu",
        "Hosakerehalli",
      ],
    },
  ];

  let total = 0;
  for (const corp of corps) {
    console.log(`Importing ${corp.name} (${corp.wards.length} wards)...`);
    for (let i = 0; i < corp.wards.length; i++) {
      const number = `${corp.prefix}-${i + 1}`;
      const name = strip(corp.wards[i]); // now actually using strip()
      await dataSource.query(
        "INSERT INTO wards (number, name, zone, state, assembly, parliamentary) VALUES ($1, $2, $3, $4, $5, $6)",
        [number, name, corp.name, "Karnataka", "TBD", "TBD"],
      );
      total++;
    }
    console.log(`✓ ${corp.name}: ${corp.wards.length} wards\n`);
  }

  console.log(`\n🎉 Total imported: ${total} wards`);
  await dataSource.destroy();
}

importAllWards().catch((err) => {
  console.error("Error:", err);
  process.exit(1);
});
